version: '3.4'

services:
  identity.api:
    image: ${DOCKER_REGISTRY}identityapi
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile

  payment.api:
    image: ${DOCKER_REGISTRY}paymentapi
    build:
      context: .
      dockerfile: src/Services/Payment/Payment.API/Dockerfile

